/* hello-world.c generated by valac 0.34.4, the Vala compiler
 * generated from hello-world.gs, do not modify */

/* GTK+ Genie Sample Code - compile with valac --pkg gtk+-2.0 hello-gtk.gs */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define TYPE_TEST_WINDOW (test_window_get_type ())
#define TEST_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEST_WINDOW, TestWindow))
#define TEST_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEST_WINDOW, TestWindowClass))
#define IS_TEST_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEST_WINDOW))
#define IS_TEST_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEST_WINDOW))
#define TEST_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEST_WINDOW, TestWindowClass))

typedef struct _TestWindow TestWindow;
typedef struct _TestWindowClass TestWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _TestWindowPrivate TestWindowPrivate;

struct _TestWindow {
	GtkWindow parent_instance;
	TestWindowPrivate * priv;
};

struct _TestWindowClass {
	GtkWindowClass parent_class;
};


static gpointer test_window_parent_class = NULL;

void _vala_main (gchar** args, int args_length1);
GType test_window_get_type (void) G_GNUC_CONST;
TestWindow* test_window_new (void);
TestWindow* test_window_construct (GType object_type);
enum  {
	TEST_WINDOW_DUMMY_PROPERTY
};
static GObject * test_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _gtk_main_quit_gtk_object_destroy (TestWindow* _sender, gpointer self);
static void _test_window___lambda4_ (TestWindow* self, GtkButton* btn);
static void __test_window___lambda4__gtk_button_clicked (GtkButton* _sender, gpointer self);


void _vala_main (gchar** args, int args_length1) {
	TestWindow* test = NULL;
	TestWindow* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = test_window_new ();
	g_object_ref_sink (_tmp0_);
	test = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) test);
	gtk_main ();
	_g_object_unref0 (test);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}


TestWindow* test_window_construct (GType object_type) {
	TestWindow * self = NULL;
	self = (TestWindow*) g_object_new (object_type, NULL);
	return self;
}


TestWindow* test_window_new (void) {
	return test_window_construct (TYPE_TEST_WINDOW);
}


static void _gtk_main_quit_gtk_object_destroy (TestWindow* _sender, gpointer self) {
	gtk_main_quit ();
}


static void _test_window___lambda4_ (TestWindow* self, GtkButton* btn) {
	GtkButton* _tmp0_ = NULL;
	g_return_if_fail (btn != NULL);
	gtk_window_set_title ((GtkWindow*) self, "Hello World");
	_tmp0_ = btn;
	gtk_button_set_label (_tmp0_, "Hello World");
}


static void __test_window___lambda4__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	_test_window___lambda4_ ((TestWindow*) self, _sender);
}


static GObject * test_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	TestWindow * self;
	GtkButton* button = NULL;
	GtkButton* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	parent_class = G_OBJECT_CLASS (test_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEST_WINDOW, TestWindow);
	gtk_window_set_title ((GtkWindow*) self, "Test Window");
	g_object_set ((GtkWindow*) self, "default-height", 250, NULL);
	g_object_set ((GtkWindow*) self, "default-width", 250, NULL);
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	g_signal_connect ((GtkObject*) self, "destroy", (GCallback) _gtk_main_quit_gtk_object_destroy, NULL);
	_tmp0_ = (GtkButton*) gtk_button_new_with_label ("Click Me");
	g_object_ref_sink (_tmp0_);
	button = _tmp0_;
	_tmp1_ = button;
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) __test_window___lambda4__gtk_button_clicked, self, 0);
	_tmp2_ = button;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp2_);
	_g_object_unref0 (button);
	return obj;
}


static void test_window_class_init (TestWindowClass * klass) {
	test_window_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = test_window_constructor;
}


static void test_window_instance_init (TestWindow * self) {
}


GType test_window_get_type (void) {
	static volatile gsize test_window_type_id__volatile = 0;
	if (g_once_init_enter (&test_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TestWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) test_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TestWindow), 0, (GInstanceInitFunc) test_window_instance_init, NULL };
		GType test_window_type_id;
		test_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "TestWindow", &g_define_type_info, 0);
		g_once_init_leave (&test_window_type_id__volatile, test_window_type_id);
	}
	return test_window_type_id__volatile;
}



